website/models.py
from . import db
from sqlalchemy.sql import func
from flask_login import UserMixin

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path, getenv
from flask_login import LoginManager
from dotenv import load_dotenv

load_dotenv()
SECRET_KEY = getenv("SECRET_KEY")

DB_NAME = "database.db"
db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = SECRET_KEY
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_NAME}"
    app.app_context().push()

    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User, Note

    if not path.exists("website/" + DB_NAME):
        db.create_all()
        print("Created Database")

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        data = request.form
        emailid = data["emailid"]
        password = data["pass"]

        user = User.query.filter_by(email=emailid).first()
        if user:
            if check_password_hash(user.password, password):
                flash("logged in successfully!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect, try again", category="error")
        else:
            flash("Email does not exist", category="error")

    return render_template("login.html", user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        data = request.form
        email = data["email"]
        fname = data["fname"]
        pass1 = data["pass1"]
        pass2 = data["pass2"]

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists", category="error")
        elif len(email) < 4:
            flash("email must be greater than 3 characters", category="error")
        elif len(fname) < 2:
            flash("first name must be greater than 1 character", category="error")
        elif pass1 != pass2:
            flash("passwords dont match", category="error")
        elif len(pass1) < 7:
            flash("password must be greater than 6 characters", category="error")
        else:
            # add user to database
            new_user = User(
                email=email,
                first_name=fname,
                password=generate_password_hash(pass1, method="sha256"),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(user, remember=True)
            flash("account created", category="success")
            return redirect(url_for("views.home"))
    return render_template("sign-up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_required, current_user
from .models import Note
from . import db


views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
@login_required
def home():
    if request.method == "POST":
        data = request.form
        note = data["note"]
        if len(note) < 1:
            flash("Note is too short", category="error")
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash("Note added successfully", category="success")

    return render_template("home.html", user=current_user)


@views.route("/delete_note")
@login_required
def delete_note():
    note_id = request.args.get("note_id")
    note_to_delete = Note.query.get(note_id)
    if note_to_delete:
        if note_to_delete.user_id == current_user.id:
            db.session.delete(note_to_delete)
            db.session.commit()

    flash("Note deleted", category="success")
    return redirect(url_for("views.home"))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Logout</a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sign-up">Sign Up</a>
                </li>


                {% endif %}

            </ul>

        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}

    {% if category=='error' %}
    <div role='alert ' class="alert alert-danger alert-dismissable fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="
            true">&times;</span>
        </button>
    </div>
    {% else %}
    <div role='alert ' class="alert alert-success alert-dismissable fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="
            true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}


    <div class="container">{% block content%}{% endblock %}</div>


    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
        crossorigin="anonymous"></script>

</body>

</html>

website/templates/home.html
{% extends 'base.html'%}
{% block title%}Home{% endblock %}

{% block content%}

<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
    <li class="list-group-item">{{ note.data }}
        <a href="{{url_for('views.delete_note', note_id = note.id)}}"><button type="button" class="close">
                <span aria-hidden="true">&times;</span>
            </button></a>
    </li>

    {% endfor %}
</ul>


<form method="POST">
    <textarea name="note" id="note" class="form-control"></textarea>
    <br>
    <div align="center">
        <button type="submit" class="btn btn-primary">Add Note</button>
    </div>




</form>




{% endblock %}

website/templates/login.html
{% extends 'base.html'%}
{% block title%}Login{% endblock %}

{% block content%} This is the login page

<form method="POST">

    <h3>Login</h3>
    <div class="form-group">
        <label for="emailid">Enter Email Address</label>
        <input type="email" class='form-control' name="emailid" id="emailid">
    </div>


    <div class="form-group">
        <label for="pass">Enter Password</label>
        <input type="password" class='form-control' name="pass" id="pass">
    </div>

    <button class="btn btn-primary" type="submit">Login</button>

</form>

{% endblock %}

website/templates/sign-up.html
{% extends 'base.html'%}
{% block title%}Sign Up{% endblock %}

{% block content%}

<form action="" method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="fname">First Name</label>
        <input type="text" class="form-control" id="fname" name="fname" placeholder="Enter First Name">
    </div>
    <div class="form-group">
        <label for="pass1">Password</label>
        <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Enter Passsword">
    </div>
    <div class="form-group">
        <label for="pass2">Confirm Password</label>
        <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Re-enter Passsword">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>





</form>


{% endblock %}